// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ding_dong/src/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(AlarmAssetAdapter());
    registerAdapter(AlarmRepeatModeAdapter());
    registerAdapter(AssetTypeAdapter());
    registerAdapter(TimeOfDayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(AlarmAssetAdapter());
    registerAdapter(AlarmRepeatModeAdapter());
    registerAdapter(AssetTypeAdapter());
    registerAdapter(TimeOfDayAdapter());
  }
}
