include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-inference: true
    strict-raw-types: true

formatter:
  page_width: 120

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
