arb-dir: lib/src/common/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/src/common/l10n/generated
untranslated-messages-file: untranslated_messages.txt
